//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessibilityInsights.Extensions.AzureDevOps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessibilityInsights.Extensions.AzureDevOps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL format is not valid. Example URL: https://dev.azure.com/fabrikam.
        /// </summary>
        public static string ADO_URL_Format_Message {
            get {
                return ResourceManager.GetString("ADO_URL_Format_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Azure Boards account.
        /// </summary>
        public static string btnNextAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnNextAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Azure Boards account.
        /// </summary>
        public static string ButtonAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ButtonAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change team.
        /// </summary>
        public static string ButtonAutomationPropertiesNameChangeTeam {
            get {
                return ResourceManager.GetString("ButtonAutomationPropertiesNameChangeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ButtonAutomationPropertiesNameRefresh {
            get {
                return ResourceManager.GetString("ButtonAutomationPropertiesNameRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create ConnectionInfo.
        /// </summary>
        public static string CantCreateConnectionInfo {
            get {
                return ResourceManager.GetString("CantCreateConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error populating Projects.
        /// </summary>
        public static string CantPopulateProjects {
            get {
                return ResourceManager.GetString("CantPopulateProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Azure Boards team.
        /// </summary>
        public static string ConnectionControl_selectTeam {
            get {
                return ResourceManager.GetString("ConnectionControl_selectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev.azure.com/fabrikam.
        /// </summary>
        public static string ConnectionDescriptionItalicized {
            get {
                return ResourceManager.GetString("ConnectionDescriptionItalicized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter desired Azure Boards link (example: .
        /// </summary>
        public static string ConnectionDescriptionPrefix {
            get {
                return ResourceManager.GetString("ConnectionDescriptionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string ConnectionDescriptionSuffix {
            get {
                return ResourceManager.GetString("ConnectionDescriptionSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Boards link.
        /// </summary>
        public static string ServerComboBoxAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ServerComboBoxAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select team project.
        /// </summary>
        public static string serverTreeviewAutomationPropertiesName {
            get {
                return ResourceManager.GetString("serverTreeviewAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Azure Boards team.
        /// </summary>
        public static string tbTeamProjectSearchAutomationPropertiesName {
            get {
                return ResourceManager.GetString("tbTeamProjectSearchAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string TextBlockTextChange {
            get {
                return ResourceManager.GetString("TextBlockTextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected team.
        /// </summary>
        public static string TextBlockTextSelectedteam {
            get {
                return ResourceManager.GetString("TextBlockTextSelectedteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error identifying the created issue. This may occur if the ID used to create the issue is removed from its Azure DevOps description. Attachments have not been uploaded..
        /// </summary>
        public static string There_was_an_error_identifying_the_created_issue_This_may_occur_if_the_ID_used_to_create_the_issue_is_removed_from_its_Azure_DevOps_description_Attachments_have_not_been_uploaded {
            get {
                return ResourceManager.GetString("There_was_an_error_identifying_the_created_issue_This_may_occur_if_the_ID_used_to" +
                        "_create_the_issue_is_removed_from_its_Azure_DevOps_description_Attachments_have_" +
                        "not_been_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to &apos;{0}&apos;. Please confirm that you have entered the correct Azure Boards link..
        /// </summary>
        public static string UnableToConnectFormattedMessage {
            get {
                return ResourceManager.GetString("UnableToConnectFormattedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to connect to Azure Boards.
        /// </summary>
        public static string WaitingToConnect {
            get {
                return ResourceManager.GetString("WaitingToConnect", resourceCulture);
            }
        }
    }
}
