//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessibilityInsights.Extensions.AzureDevOps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessibilityInsights.Extensions.AzureDevOps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev.azure.com/fabrikam.
        /// </summary>
        internal static string accountPlaceholderText {
            get {
                return ResourceManager.GetString("accountPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btnNextAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnNextAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string ButtonAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ButtonAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change team.
        /// </summary>
        internal static string ButtonAutomationPropertiesNameChangeTeam {
            get {
                return ResourceManager.GetString("ButtonAutomationPropertiesNameChangeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ButtonAutomationPropertiesNameRefresh {
            get {
                return ResourceManager.GetString("ButtonAutomationPropertiesNameRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your team.
        /// </summary>
        internal static string ConnectionControl_selectTeam {
            get {
                return ResourceManager.GetString("ConnectionControl_selectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        internal static string ConnectionControl_serverURL {
            get {
                return ResourceManager.GetString("ConnectionControl_serverURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create bugs and save test results, you must first enter the Azure DevOps URL and click Next to sign in..
        /// </summary>
        internal static string connectionInstrText {
            get {
                return ResourceManager.GetString("connectionInstrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the full Azure DevOps URL such as https://dev.azure.com/fabrikam.
        /// </summary>
        internal static string ServerComboBoxAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ServerComboBoxAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team project.
        /// </summary>
        internal static string serverTreeviewAutomationPropertiesName {
            get {
                return ResourceManager.GetString("serverTreeviewAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for team project.
        /// </summary>
        internal static string tbTeamProjectSearchAutomationPropertiesName {
            get {
                return ResourceManager.GetString("tbTeamProjectSearchAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string TextBlockTextChange {
            get {
                return ResourceManager.GetString("TextBlockTextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected team.
        /// </summary>
        internal static string TextBlockTextSelectedteam {
            get {
                return ResourceManager.GetString("TextBlockTextSelectedteam", resourceCulture);
            }
        }
    }
}
