//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessibilityInsights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessibilityInsights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve.
        /// </summary>
        public static string AutomationNameTelemetryMode {
            get {
                return ResourceManager.GetString("AutomationNameTelemetryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Bar.
        /// </summary>
        public static string bdLeftNavAutomationPropertiesName {
            get {
                return ResourceManager.GetString("bdLeftNavAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beaker click animation.
        /// </summary>
        public static string BeakerAnimationControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("BeakerAnimationControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign into AzureDevOps and configure sign in settings.
        /// </summary>
        public static string btnAccountConfigAutomationPropertiesHelpText {
            get {
                return ResourceManager.GetString("btnAccountConfigAutomationPropertiesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in 2 of 2.
        /// </summary>
        public static string btnAccountConfigAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnAccountConfigAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string btnAccountConfigToolTip {
            get {
                return ResourceManager.GetString("btnAccountConfigToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color contrast analyzer 3 of 3.
        /// </summary>
        public static string btnCCAAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnCCAAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCA.
        /// </summary>
        public static string btnCCAToolTip {
            get {
                return ResourceManager.GetString("btnCCAToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter: Close Button Click.
        /// </summary>
        public static string btnClose_ClickDebugMessage {
            get {
                return ResourceManager.GetString("btnClose_ClickDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnCloseAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnCloseAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close welcome screen.
        /// </summary>
        public static string btnCloseScreenAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnCloseScreenAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure settings of Accessibility Insights for Windows.
        /// </summary>
        public static string btnConfigAutomationPropertiesHelpText {
            get {
                return ResourceManager.GetString("btnConfigAutomationPropertiesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings 1 of 2.
        /// </summary>
        public static string btnConfigAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnConfigAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnConfigAutomationPropertiesNameNoBugFiling {
            get {
                return ResourceManager.GetString("btnConfigAutomationPropertiesNameNoBugFiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings....
        /// </summary>
        public static string btnConfigToolTip {
            get {
                return ResourceManager.GetString("btnConfigToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnExitContentTelemetryOK {
            get {
                return ResourceManager.GetString("btnExitContentTelemetryOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show documentation on how to use.
        /// </summary>
        public static string btnHelpAutomationPropertiesHelpText {
            get {
                return ResourceManager.GetString("btnHelpAutomationPropertiesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string btnHelpAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnHelpAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string btnHelpToolTip {
            get {
                return ResourceManager.GetString("btnHelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter Off.
        /// </summary>
        public static string btnHilighterAutomationPropertiesNameOff {
            get {
                return ResourceManager.GetString("btnHilighterAutomationPropertiesNameOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter On.
        /// </summary>
        public static string btnHilighterAutomationPropertiesNameOn {
            get {
                return ResourceManager.GetString("btnHilighterAutomationPropertiesNameOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect mode 1 of 3.
        /// </summary>
        public static string btnInspectAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnInspectAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        public static string btnInspectToolTip {
            get {
                return ResourceManager.GetString("btnInspectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is not an Accessibility Insights for Windows file..
        /// </summary>
        public static string btnLoad_ClickDialogErrorMessage {
            get {
                return ResourceManager.GetString("btnLoad_ClickDialogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Accessibility Insights for Windows file.
        /// </summary>
        public static string btnLoad_ClickDialogTitle {
            get {
                return ResourceManager.GetString("btnLoad_ClickDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load test or event file.
        /// </summary>
        public static string btnLoadAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnLoadAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string btnMaxAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnMaxAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string btnMinAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnMinAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close.
        /// </summary>
        public static string btnOkContent {
            get {
                return ResourceManager.GetString("btnOkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume UIA Tree.
        /// </summary>
        public static string btnPauseAutomationPropertiesNameOff {
            get {
                return ResourceManager.GetString("btnPauseAutomationPropertiesNameOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause UIA Tree.
        /// </summary>
        public static string btnPauseAutomationPropertiesNameOn {
            get {
                return ResourceManager.GetString("btnPauseAutomationPropertiesNameOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerun tests.
        /// </summary>
        public static string btnRefreshAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnRefreshAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerun tests.
        /// </summary>
        public static string btnRefreshToolTip {
            get {
                return ResourceManager.GetString("btnRefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes.
        /// </summary>
        public static string btnReleaseNotesText {
            get {
                return ResourceManager.GetString("btnReleaseNotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnSaveAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests FastPass mode 2 of 3.
        /// </summary>
        public static string btnTestAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnTestAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string btnTestToolTip {
            get {
                return ResourceManager.GetString("btnTestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter integer number to set delay second(s)..
        /// </summary>
        public static string btnTimer_ClickMessage {
            get {
                return ResourceManager.GetString("btnTimer_ClickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string btnTimerAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnTimerAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string btnUpdateLaterText {
            get {
                return ResourceManager.GetString("btnUpdateLaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        public static string btnUpdateNowText {
            get {
                return ResourceManager.GetString("btnUpdateNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the video. please use this URL to open page.
        /// {0}.
        /// </summary>
        public static string btnVideo_ClickException {
            get {
                return ResourceManager.GetString("btnVideo_ClickException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string cbiElementAutomationPropertiesName {
            get {
                return ResourceManager.GetString("cbiElementAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string cbiElementContent {
            get {
                return ResourceManager.GetString("cbiElementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire app.
        /// </summary>
        public static string cbiEntireAppAutomationPropertiesName {
            get {
                return ResourceManager.GetString("cbiEntireAppAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire app.
        /// </summary>
        public static string cbiEntireAppContent {
            get {
                return ResourceManager.GetString("cbiEntireAppContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to select.
        /// </summary>
        public static string cbSelectionScopeAutomationPropertiesName {
            get {
                return ResourceManager.GetString("cbSelectionScopeAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test start up page.
        /// </summary>
        public static string CCAModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("CCAModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to enable telemetry.
        /// </summary>
        public static string ckbxAgreeToHelp {
            get {
                return ResourceManager.GetString("ckbxAgreeToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Don&apos;t show this again.
        /// </summary>
        public static string ckbxDontShowContent {
            get {
                return ResourceManager.GetString("ckbxDontShowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run automated checks, click on the beaker icon of the highlighted element or use the keyboard shortcut and press .
        /// </summary>
        public static string clickOnTheBeaker {
            get {
                return ResourceManager.GetString("clickOnTheBeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Contrast.
        /// </summary>
        public static string colorContrast {
            get {
                return ResourceManager.GetString("colorContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page.
        /// </summary>
        public static string ConfigurationModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ConfigurationModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content container.
        /// </summary>
        public static string ctrlConfigurationModeAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ctrlConfigurationModeAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command bar.
        /// </summary>
        public static string ctrlNamedCommandbarAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ctrlNamedCommandbarAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event information.
        /// </summary>
        public static string ctrlTabsAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ctrlTabsAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element information.
        /// </summary>
        public static string ctrlTabsElementAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ctrlTabsElementAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not proper hotkey combination. Hotkey should be [Shift|Ctrl|Alt|Window]+[a single key including function key].
        /// </summary>
        public static string CultureInfoErrorMessage {
            get {
                return ResourceManager.GetString("CultureInfoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for target.
        /// </summary>
        public static string detectedFailuresMessagePart1 {
            get {
                return ResourceManager.GetString("detectedFailuresMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failures were detected..
        /// </summary>
        public static string detectedFailuresMessagePart2 {
            get {
                return ResourceManager.GetString("detectedFailuresMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event page.
        /// </summary>
        public static string EventModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("EventModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard focus animation.
        /// </summary>
        public static string FocusAnimationControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("FocusAnimationControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string gdConfigBtnCloseAutomationPropertiesName {
            get {
                return ResourceManager.GetString("gdConfigBtnCloseAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string gdConfigLabelContent {
            get {
                return ResourceManager.GetString("gdConfigLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change horizontal size of Hierarchy pane.
        /// </summary>
        public static string gsMidAutomationPropertiesHelpText {
            get {
                return ResourceManager.GetString("gsMidAutomationPropertiesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change horizontal size of Hierarchy pane.
        /// </summary>
        public static string gsMidAutomationPropertiesHelpText1 {
            get {
                return ResourceManager.GetString("gsMidAutomationPropertiesHelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splitter for Hierarchy pane.
        /// </summary>
        public static string gsMidAutomationPropertiesName {
            get {
                return ResourceManager.GetString("gsMidAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Insights has lost the connection to the application. Select the application or element and run tests again..
        /// </summary>
        public static string HandleFailedSelectionResetConnectionLostMessage {
            get {
                return ResourceManager.GetString("HandleFailedSelectionResetConnectionLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        public static string HandleLogoutRequestSignIn {
            get {
                return ResourceManager.GetString("HandleLogoutRequestSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an element first before starting Event page..
        /// </summary>
        public static string HandleRequestRecordingByHotkeySelectElementMessage {
            get {
                return ResourceManager.GetString("HandleRequestRecordingByHotkeySelectElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful shortcuts.
        /// </summary>
        public static string helpfulShortcutsText {
            get {
                return ResourceManager.GetString("helpfulShortcutsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open link..
        /// </summary>
        public static string hlLink_RequestNavigateException {
            get {
                return ResourceManager.GetString("hlLink_RequestNavigateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global menus.
        /// </summary>
        public static string ictMainMenuBottopAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ictMainMenuBottopAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon.
        /// </summary>
        public static string ImageAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ImageAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started video thumbnail.
        /// </summary>
        public static string imageVideoAutomationPropertiesName {
            get {
                return ResourceManager.GetString("imageVideoAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your help.
        /// </summary>
        public static string LabelContentTelemetryDialogLabel {
            get {
                return ResourceManager.GetString("LabelContentTelemetryDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Inspect.
        /// </summary>
        public static string liveInspect {
            get {
                return ResourceManager.GetString("liveInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available properties.
        /// </summary>
        public static string LiveModeControl_CopyToClipboard_Available_properties {
            get {
                return ResourceManager.GetString("LiveModeControl_CopyToClipboard_Available_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glimpse: {0}.
        /// </summary>
        public static string LiveModeControl_CopyToClipboard_Glimpse_0 {
            get {
                return ResourceManager.GetString("LiveModeControl_CopyToClipboard_Glimpse_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Inspect page.
        /// </summary>
        public static string LiveModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("LiveModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        public static string MainWindow_AutomationPropertiesName_0_1_2 {
            get {
                return ResourceManager.GetString("MainWindow_AutomationPropertiesName_0_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load the selected file: {0}.
        /// </summary>
        public static string MainWindow_HandleLoadingEventData_Couldnt_load_the_selected_file_0 {
            get {
                return ResourceManager.GetString("MainWindow_HandleLoadingEventData_Couldnt_load_the_selected_file_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available..
        /// </summary>
        public static string MainWindow_ShowUpgradeDialog_An_update_is_available {
            get {
                return ResourceManager.GetString("MainWindow_ShowUpgradeDialog_An_update_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is required..
        /// </summary>
        public static string MainWindow_ShowUpgradeDialog_An_update_is_required {
            get {
                return ResourceManager.GetString("MainWindow_ShowUpgradeDialog_An_update_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} of {2}.
        /// </summary>
        public static string MainWindow_UpdateMainCommandButtons_0_1_of_2 {
            get {
                return ResourceManager.GetString("MainWindow_UpdateMainCommandButtons_0_1_of_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Insights for Windows - {0}.
        /// </summary>
        public static string MainWindow_UpdateTitleString_Accessibility_Insights_for_Windows_0 {
            get {
                return ResourceManager.GetString("MainWindow_UpdateTitleString_Accessibility_Insights_for_Windows_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Insights for Windows.
        /// </summary>
        public static string MainWindowWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize or activate the main window..
        /// </summary>
        public static string minmizeOrActivateWindowText {
            get {
                return ResourceManager.GetString("minmizeOrActivateWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start test in 5 seconds.
        /// </summary>
        public static string miTimerAutomationPropertiesName {
            get {
                return ResourceManager.GetString("miTimerAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode is enabled.
        /// </summary>
        public static string ModeIsEnabled {
            get {
                return ResourceManager.GetString("ModeIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information visit.
        /// </summary>
        public static string moreInformationText {
            get {
                return ResourceManager.GetString("moreInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element&apos;s bounding rectangle is empty (app minimized?)- no screenshot is available..
        /// </summary>
        public static string noScreenShotAvailableMessage {
            get {
                return ResourceManager.GetString("noScreenShotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Make sure the server URL is complete (e.g. https://accountname.visualstudio.com).
        /// </summary>
        public static string NotifyLoginUnsuccessfulDialogMessage {
            get {
                return ResourceManager.GetString("NotifyLoginUnsuccessfulDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: MainWindow Closed.
        /// </summary>
        public static string onClosedDebugMessage {
            get {
                return ResourceManager.GetString("onClosedDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, trying to sign in!.
        /// </summary>
        public static string onLoadedDialogWaitMessage {
            get {
                return ResourceManager.GetString("onLoadedDialogWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string paused {
            get {
                return ResourceManager.GetString("paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop listening first to move back to live..
        /// </summary>
        public static string PleaseMoveBackToLiveDialogMessage {
            get {
                return ResourceManager.GetString("PleaseMoveBackToLiveDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the mouse to hover over or use the keyboard to select an element that you want to inspect..
        /// </summary>
        public static string PleaseUseMouseToHover {
            get {
                return ResourceManager.GetString("PleaseUseMouseToHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the URL.\nURL:.
        /// </summary>
        public static string ReleaseNotes_ClickLoadErrorMessage {
            get {
                return ResourceManager.GetString("ReleaseNotes_ClickLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL was not properly formatted.\nURL:.
        /// </summary>
        public static string ReleaseNotes_ClickURLErrorMessage {
            get {
                return ResourceManager.GetString("ReleaseNotes_ClickURLErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results in UIA Tree.
        /// </summary>
        public static string resultsInUIATree {
            get {
                return ResourceManager.GetString("resultsInUIATree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tests on the selected element anytime..
        /// </summary>
        public static string runSelectedTestText {
            get {
                return ResourceManager.GetString("runSelectedTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By opting into telemetry, you.
        /// </summary>
        public static string RunTextHelpCommunity1 {
            get {
                return ResourceManager.GetString("RunTextHelpCommunity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help the community.
        /// </summary>
        public static string RunTextHelpCommunity2 {
            get {
                return ResourceManager.GetString("RunTextHelpCommunity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to develop inclusive software.
        ///
        ///We collect anonymized data to identify the top accessibility issues found by users. This will help focus the accessibility tools and standards community to improve guidelines, rules engines, and features..
        /// </summary>
        public static string RunTextHelpCommunity3 {
            get {
                return ResourceManager.GetString("RunTextHelpCommunity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change this choice anytime under Settings..
        /// </summary>
        public static string RunTextPrivacyStatement {
            get {
                return ResourceManager.GetString("RunTextPrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save the file: {0}.
        /// </summary>
        public static string SaveException {
            get {
                return ResourceManager.GetString("SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the first {0:N0} elements are being scanned. You will not be able to save the results or file any bugs from this scan..
        /// </summary>
        public static string SetElementCultureInfoFormatMessage {
            get {
                return ResourceManager.GetString("SetElementCultureInfoFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t initiate Event recording, please go back to Inspect mode and select an element again..
        /// </summary>
        public static string SetElementException {
            get {
                return ResourceManager.GetString("SetElementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect Test Detail of {0}.
        /// </summary>
        public static string SetElementInspectTestDetail {
            get {
                return ResourceManager.GetString("SetElementInspectTestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift + F8.
        /// </summary>
        public static string ShiftF8 {
            get {
                return ResourceManager.GetString("ShiftF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Inspect page.
        /// </summary>
        public static string SnapshotModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("SnapshotModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No element is selected. please select an element first..
        /// </summary>
        public static string StartElementDetailViewNoElementIsSelectedMessage {
            get {
                return ResourceManager.GetString("StartElementDetailViewNoElementIsSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The select element is not available any more, please select a new one..
        /// </summary>
        public static string StartEventsModeElementNotAvailableMessage {
            get {
                return ResourceManager.GetString("StartEventsModeElementNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the selected file.
        ///Please ensure that you are opening an valid test file using the most recent release of Accessibility Insights for Windows (https://aka.ms/AccessibilityInsights).
        /// </summary>
        public static string StartLoadingSnapshotLoadFileException {
            get {
                return ResourceManager.GetString("StartLoadingSnapshotLoadFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string StartUpModeControl_btnExit {
            get {
                return ResourceManager.GetString("StartUpModeControl_btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome page.
        /// </summary>
        public static string StartUpModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("StartUpModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach now.
        /// </summary>
        public static string SupportDebuggingDialogMessage {
            get {
                return ResourceManager.GetString("SupportDebuggingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following feature is for certain internal dogfooders to help diagnose our preliminary test result de-duping logic. The UX and tool may cause unpredictable behavior..
        /// </summary>
        public static string TabControl_SelectionChangedDialogMessage {
            get {
                return ResourceManager.GetString("TabControl_SelectionChangedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastPass.
        /// </summary>
        public static string tabControlLabelContent {
            get {
                return ResourceManager.GetString("tabControlLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to select:.
        /// </summary>
        public static string tbComboboxLabelText {
            get {
                return ResourceManager.GetString("tbComboboxLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated checks in FastPass.
        /// </summary>
        public static string tbiAutomatedChecksAutomationPropertiesName {
            get {
                return ResourceManager.GetString("tbiAutomatedChecksAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Checks.
        /// </summary>
        public static string tbiAutomatedChecksHeader {
            get {
                return ResourceManager.GetString("tbiAutomatedChecksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab stops in FastPass.
        /// </summary>
        public static string tbiTabStopAutomationPropertiesName {
            get {
                return ResourceManager.GetString("tbiTabStopAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Stops.
        /// </summary>
        public static string tbiTabStopHeader {
            get {
                return ResourceManager.GetString("tbiTabStopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Test in.
        /// </summary>
        public static string tbTimerText1 {
            get {
                return ResourceManager.GetString("tbTimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second(s).
        /// </summary>
        public static string tbTimerText2 {
            get {
                return ResourceManager.GetString("tbTimerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string tbVideoText1 {
            get {
                return ResourceManager.GetString("tbVideoText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about Accessibility Insights for Windows with this 4-minute introductory video..
        /// </summary>
        public static string tbVideoText2 {
            get {
                return ResourceManager.GetString("tbVideoText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timer in.
        /// </summary>
        public static string tbxTimer_TextChangedText1 {
            get {
                return ResourceManager.GetString("tbxTimer_TextChangedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string tbxTimer_TextChangedText2 {
            get {
                return ResourceManager.GetString("tbxTimer_TextChangedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string tcTabsAboutHeader {
            get {
                return ResourceManager.GetString("tcTabsAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string tcTabsApplicationHeader {
            get {
                return ResourceManager.GetString("tcTabsApplicationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string tcTabsConnectionHeader {
            get {
                return ResourceManager.GetString("tcTabsConnectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string tcTabsFeedbackHeader {
            get {
                return ResourceManager.GetString("tcTabsFeedbackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string tcTabsTestHeader {
            get {
                return ResourceManager.GetString("tcTabsTestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        public static string tcTabsWhatsNewHeader {
            get {
                return ResourceManager.GetString("tcTabsWhatsNewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Link {0}.
        /// </summary>
        public static string TelemetryDialog_Hyperlink_RequestNavigate_Invalid_Link {
            get {
                return ResourceManager.GetString("TelemetryDialog_Hyperlink_RequestNavigate_Invalid_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test page.
        /// </summary>
        public static string TestModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("TestModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string tests {
            get {
                return ResourceManager.GetString("tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color contrast.
        /// </summary>
        public static string TitleTextMapCCA {
            get {
                return ResourceManager.GetString("TitleTextMapCCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string TitleTextMapEvents {
            get {
                return ResourceManager.GetString("TitleTextMapEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events (Loaded data).
        /// </summary>
        public static string TitleTextMapEventsLoad {
            get {
                return ResourceManager.GetString("TitleTextMapEventsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events (Recording).
        /// </summary>
        public static string TitleTextMapEventsRecord {
            get {
                return ResourceManager.GetString("TitleTextMapEventsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string TitleTextMapEventsStopped {
            get {
                return ResourceManager.GetString("TitleTextMapEventsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting....
        /// </summary>
        public static string TitleTextMapExit {
            get {
                return ResourceManager.GetString("TitleTextMapExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect - Live.
        /// </summary>
        public static string TitleTextMapInspectLive {
            get {
                return ResourceManager.GetString("TitleTextMapInspectLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect (Scanning).
        /// </summary>
        public static string TitleTextMapInspectScan {
            get {
                return ResourceManager.GetString("TitleTextMapInspectScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TitleTextMapStart {
            get {
                return ResourceManager.GetString("TitleTextMapStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - Element details.
        /// </summary>
        public static string TitleTextMapTestElementDetails {
            get {
                return ResourceManager.GetString("TitleTextMapTestElementDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - How to Fix.
        /// </summary>
        public static string TitleTextMapTestHowToFix {
            get {
                return ResourceManager.GetString("TitleTextMapTestHowToFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - No selection.
        /// </summary>
        public static string TitleTextMapTestNoSelection {
            get {
                return ResourceManager.GetString("TitleTextMapTestNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - Test results.
        /// </summary>
        public static string TitleTextMapTestResults {
            get {
                return ResourceManager.GetString("TitleTextMapTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test (Scanning).
        /// </summary>
        public static string TitleTextMapTestScan {
            get {
                return ResourceManager.GetString("TitleTextMapTestScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - Tab Stops.
        /// </summary>
        public static string TitleTextMapTestTabStops {
            get {
                return ResourceManager.GetString("TitleTextMapTestTabStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter / toggle event recording on the selected element..
        /// </summary>
        public static string toggleEventText {
            get {
                return ResourceManager.GetString("toggleEventText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available.
        /// </summary>
        public static string UpdateDialogWindowTitle {
            get {
                return ResourceManager.GetString("UpdateDialogWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as {0}.
        /// </summary>
        public static string UpdateMainWindowLoginFieldsSignedInAs {
            get {
                return ResourceManager.GetString("UpdateMainWindowLoginFieldsSignedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Insights for Windows.
        /// </summary>
        public static string UpdateTitleStringTitle {
            get {
                return ResourceManager.GetString("UpdateTitleStringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - UIAccess.
        /// </summary>
        public static string UpdateVersionStringUIAccess {
            get {
                return ResourceManager.GetString("UpdateVersionStringUIAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver {0}.
        /// </summary>
        public static string UpdateVersionStringVer {
            get {
                return ResourceManager.GetString("UpdateVersionStringVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Accessibility Insights for Windows.
        /// </summary>
        public static string WelcomeToAccessibilityInsightsForWindowsLabelContent {
            get {
                return ResourceManager.GetString("WelcomeToAccessibilityInsightsForWindowsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter: Closing MainWindow.
        /// </summary>
        public static string Window_ClosingDebugMessage {
            get {
                return ResourceManager.GetString("Window_ClosingDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while closing MainWindow.
        /// </summary>
        public static string Window_ClosingException {
            get {
                return ResourceManager.GetString("Window_ClosingException", resourceCulture);
            }
        }
    }
}
