//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessibilityInsights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessibilityInsights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know? Automated checks can detect some common accessibility problems, such as missing or invalid properties. However, most accessibility problems can be identified only through manual testing..
        /// </summary>
        public static string AutomatedChecksRole {
            get {
                return ResourceManager.GetString("AutomatedChecksRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Bar.
        /// </summary>
        public static string bdLeftNavAutomationPropertiesName {
            get {
                return ResourceManager.GetString("bdLeftNavAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign into AzureDevOps and configure sign in settings.
        /// </summary>
        public static string btnAccountConfigAutomationPropertiesHelpText {
            get {
                return ResourceManager.GetString("btnAccountConfigAutomationPropertiesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in 2 of 2.
        /// </summary>
        public static string btnAccountConfigAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnAccountConfigAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string btnAccountConfigToolTip {
            get {
                return ResourceManager.GetString("btnAccountConfigToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color contrast analyzer 3 of 3.
        /// </summary>
        public static string btnCCAAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnCCAAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string btnCCAToolTip {
            get {
                return ResourceManager.GetString("btnCCAToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter: Close Button Click.
        /// </summary>
        public static string btnClose_ClickDebugMessage {
            get {
                return ResourceManager.GetString("btnClose_ClickDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnCloseAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnCloseAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure settings of Accessibility Insights for Windows.
        /// </summary>
        public static string btnConfigAutomationPropertiesHelpText {
            get {
                return ResourceManager.GetString("btnConfigAutomationPropertiesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings 1 of 2.
        /// </summary>
        public static string btnConfigAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnConfigAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnConfigAutomationPropertiesNameNoBugFiling {
            get {
                return ResourceManager.GetString("btnConfigAutomationPropertiesNameNoBugFiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings....
        /// </summary>
        public static string btnConfigToolTip {
            get {
                return ResourceManager.GetString("btnConfigToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show documentation on how to use.
        /// </summary>
        public static string btnHelpAutomationPropertiesHelpText {
            get {
                return ResourceManager.GetString("btnHelpAutomationPropertiesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string btnHelpAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnHelpAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string btnHelpToolTip {
            get {
                return ResourceManager.GetString("btnHelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter Off.
        /// </summary>
        public static string btnHilighterAutomationPropertiesNameOff {
            get {
                return ResourceManager.GetString("btnHilighterAutomationPropertiesNameOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter On.
        /// </summary>
        public static string btnHilighterAutomationPropertiesNameOn {
            get {
                return ResourceManager.GetString("btnHilighterAutomationPropertiesNameOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect mode 1 of 3.
        /// </summary>
        public static string btnInspectAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnInspectAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        public static string btnInspectToolTip {
            get {
                return ResourceManager.GetString("btnInspectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Accessibility Insights for Windows file.
        /// </summary>
        public static string btnLoad_ClickDialogTitle {
            get {
                return ResourceManager.GetString("btnLoad_ClickDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load test or event file.
        /// </summary>
        public static string btnLoadAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnLoadAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string btnMaxAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnMaxAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string btnMinAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnMinAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close.
        /// </summary>
        public static string btnOkContent {
            get {
                return ResourceManager.GetString("btnOkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume UI Automation Tree.
        /// </summary>
        public static string btnPauseAutomationPropertiesNameOff {
            get {
                return ResourceManager.GetString("btnPauseAutomationPropertiesNameOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause UI Automation Tree.
        /// </summary>
        public static string btnPauseAutomationPropertiesNameOn {
            get {
                return ResourceManager.GetString("btnPauseAutomationPropertiesNameOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerun tests.
        /// </summary>
        public static string btnRefreshAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnRefreshAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerun tests.
        /// </summary>
        public static string btnRefreshToolTip {
            get {
                return ResourceManager.GetString("btnRefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnSaveAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests FastPass mode 2 of 3.
        /// </summary>
        public static string btnTestAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnTestAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string btnTestToolTip {
            get {
                return ResourceManager.GetString("btnTestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter integer number to set delay second(s)..
        /// </summary>
        public static string btnTimer_ClickMessage {
            get {
                return ResourceManager.GetString("btnTimer_ClickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string btnTimerAutomationPropertiesName {
            get {
                return ResourceManager.GetString("btnTimerAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string cbiElementAutomationPropertiesName {
            get {
                return ResourceManager.GetString("cbiElementAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string cbiElementContent {
            get {
                return ResourceManager.GetString("cbiElementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire app.
        /// </summary>
        public static string cbiEntireAppAutomationPropertiesName {
            get {
                return ResourceManager.GetString("cbiEntireAppAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire app.
        /// </summary>
        public static string cbiEntireAppContent {
            get {
                return ResourceManager.GetString("cbiEntireAppContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to select.
        /// </summary>
        public static string cbSelectionScopeAutomationPropertiesName {
            get {
                return ResourceManager.GetString("cbSelectionScopeAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test start up page.
        /// </summary>
        public static string CCAModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("CCAModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Contrast analyzer.
        /// </summary>
        public static string colorContrast {
            get {
                return ResourceManager.GetString("colorContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Insights for Windows was unable to change channels. Please check your internet connection and try again later..
        /// </summary>
        public static string ConfigurationModeControl_VersionSwitcherException {
            get {
                return ResourceManager.GetString("ConfigurationModeControl_VersionSwitcherException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page.
        /// </summary>
        public static string ConfigurationModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ConfigurationModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content container.
        /// </summary>
        public static string ctrlConfigurationModeAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ctrlConfigurationModeAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command bar.
        /// </summary>
        public static string ctrlNamedCommandbarAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ctrlNamedCommandbarAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event information.
        /// </summary>
        public static string ctrlTabsAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ctrlTabsAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element information.
        /// </summary>
        public static string ctrlTabsElementAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ctrlTabsElementAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not proper hotkey combination. Hotkey should be [Shift|Ctrl|Alt|Window]+[a single key including function key].
        /// </summary>
        public static string CultureInfoErrorMessage {
            get {
                return ResourceManager.GetString("CultureInfoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for target.
        /// </summary>
        public static string detectedFailuresMessagePart1 {
            get {
                return ResourceManager.GetString("detectedFailuresMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failures were detected..
        /// </summary>
        public static string detectedFailuresMessagePart2 {
            get {
                return ResourceManager.GetString("detectedFailuresMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event page.
        /// </summary>
        public static string EventModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("EventModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string gdConfigBtnCloseAutomationPropertiesName {
            get {
                return ResourceManager.GetString("gdConfigBtnCloseAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string gdConfigLabelContent {
            get {
                return ResourceManager.GetString("gdConfigLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change horizontal size of Hierarchy pane.
        /// </summary>
        public static string gsMidAutomationPropertiesHelpText {
            get {
                return ResourceManager.GetString("gsMidAutomationPropertiesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splitter for Hierarchy pane.
        /// </summary>
        public static string gsMidAutomationPropertiesName {
            get {
                return ResourceManager.GetString("gsMidAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Insights has lost the connection to the application. Select the application or element and run tests again..
        /// </summary>
        public static string HandleFailedSelectionResetConnectionLostMessage {
            get {
                return ResourceManager.GetString("HandleFailedSelectionResetConnectionLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        public static string HandleLogoutRequestSignIn {
            get {
                return ResourceManager.GetString("HandleLogoutRequestSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an element first before starting Event page..
        /// </summary>
        public static string HandleRequestRecordingByHotkeySelectElementMessage {
            get {
                return ResourceManager.GetString("HandleRequestRecordingByHotkeySelectElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open link..
        /// </summary>
        public static string hlLink_RequestNavigateException {
            get {
                return ResourceManager.GetString("hlLink_RequestNavigateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global menus.
        /// </summary>
        public static string ictMainMenuBottopAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ictMainMenuBottopAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon.
        /// </summary>
        public static string ImageAutomationPropertiesName {
            get {
                return ResourceManager.GetString("ImageAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Inspect.
        /// </summary>
        public static string liveInspect {
            get {
                return ResourceManager.GetString("liveInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available properties.
        /// </summary>
        public static string LiveModeControl_CopyToClipboard_Available_properties {
            get {
                return ResourceManager.GetString("LiveModeControl_CopyToClipboard_Available_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glimpse: {0}.
        /// </summary>
        public static string LiveModeControl_CopyToClipboard_Glimpse_0 {
            get {
                return ResourceManager.GetString("LiveModeControl_CopyToClipboard_Glimpse_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . You can also focus on the element, then press.
        /// </summary>
        public static string LiveModeControl_FocusOnElement {
            get {
                return ResourceManager.GetString("LiveModeControl_FocusOnElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin inspecting a UI Automation element, hover over the element within the target application or set keyboard focus on the element. To inspect its properties, bring focus back to Accessibility Insights for Windows by pressing.
        /// </summary>
        public static string LiveModeControl_HoverOverElement {
            get {
                return ResourceManager.GetString("LiveModeControl_HoverOverElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about automated checks.
        /// </summary>
        public static string LiveModeControl_LearnMoreAutomated {
            get {
                return ResourceManager.GetString("LiveModeControl_LearnMoreAutomated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about Inspect.
        /// </summary>
        public static string LiveModeControl_LearnMoreInspect {
            get {
                return ResourceManager.GetString("LiveModeControl_LearnMoreInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run automated checks, hover over the element within the target application and select the Test icon.
        /// </summary>
        public static string LiveModeControl_RunAutomatedChecks {
            get {
                return ResourceManager.GetString("LiveModeControl_RunAutomatedChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Inspect page.
        /// </summary>
        public static string LiveModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("LiveModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        public static string LocalizedControlType_Page {
            get {
                return ResourceManager.GetString("LocalizedControlType_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        public static string MainWindow_AutomationPropertiesName_0_1_2 {
            get {
                return ResourceManager.GetString("MainWindow_AutomationPropertiesName_0_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MainWindow_DefaultTimerDelayInSeconds {
            get {
                return ResourceManager.GetString("MainWindow_DefaultTimerDelayInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string MainWindow_One {
            get {
                return ResourceManager.GetString("MainWindow_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _?.
        /// </summary>
        public static string MainWindow_QuestionMark {
            get {
                return ResourceManager.GetString("MainWindow_QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string MainWindow_Two {
            get {
                return ResourceManager.GetString("MainWindow_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} of {2}.
        /// </summary>
        public static string MainWindow_UpdateMainCommandButtons_0_1_of_2 {
            get {
                return ResourceManager.GetString("MainWindow_UpdateMainCommandButtons_0_1_of_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Insights for Windows - {0}.
        /// </summary>
        public static string MainWindow_UpdateTitleString_Accessibility_Insights_for_Windows_0 {
            get {
                return ResourceManager.GetString("MainWindow_UpdateTitleString_Accessibility_Insights_for_Windows_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Insights for Windows.
        /// </summary>
        public static string MainWindowWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start test in 5 seconds.
        /// </summary>
        public static string miTimerAutomationPropertiesName {
            get {
                return ResourceManager.GetString("miTimerAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mode is enabled.
        /// </summary>
        public static string ModeIsEnabled {
            get {
                return ResourceManager.GetString("ModeIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element&apos;s bounding rectangle is empty (app minimized?)- no screenshot is available..
        /// </summary>
        public static string noScreenShotAvailableMessage {
            get {
                return ResourceManager.GetString("noScreenShotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: MainWindow Closed.
        /// </summary>
        public static string onClosedDebugMessage {
            get {
                return ResourceManager.GetString("onClosedDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem updating the application. Please check your internet connection and try again..
        /// </summary>
        public static string OptionalUpdateFailedUnknown {
            get {
                return ResourceManager.GetString("OptionalUpdateFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panes can be set only once.
        /// </summary>
        public static string PanesCanBeSetOnlyOnce {
            get {
                return ResourceManager.GetString("PanesCanBeSetOnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string paused {
            get {
                return ResourceManager.GetString("paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop listening first to move back to live..
        /// </summary>
        public static string PleaseMoveBackToLiveDialogMessage {
            get {
                return ResourceManager.GetString("PleaseMoveBackToLiveDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem updating the application. Because this is a required update, the app will be shut down. Please check your internet connection and try again..
        /// </summary>
        public static string RequiredUpdateFailedUnknown {
            get {
                return ResourceManager.GetString("RequiredUpdateFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results in UI Automation Tree.
        /// </summary>
        public static string resultsInUIATree {
            get {
                return ResourceManager.GetString("resultsInUIATree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save the file: {0}.
        /// </summary>
        public static string SaveException {
            get {
                return ResourceManager.GetString("SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string SentenceEndPeriod {
            get {
                return ResourceManager.GetString("SentenceEndPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the first {0:N0} elements are being scanned. You will not be able to save the results or file any bugs from this scan..
        /// </summary>
        public static string SetElementCultureInfoFormatMessage {
            get {
                return ResourceManager.GetString("SetElementCultureInfoFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t initiate Event recording, please go back to Inspect mode and select an element again..
        /// </summary>
        public static string SetElementException {
            get {
                return ResourceManager.GetString("SetElementException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect Test Detail of {0}.
        /// </summary>
        public static string SetElementInspectTestDetail {
            get {
                return ResourceManager.GetString("SetElementInspectTestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available patterns:.
        /// </summary>
        public static string SnapshotModeControl_AvailablePatterns {
            get {
                return ResourceManager.GetString("SnapshotModeControl_AvailablePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available properties.
        /// </summary>
        public static string SnapshotModeControl_AvailableProperties {
            get {
                return ResourceManager.GetString("SnapshotModeControl_AvailableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glimpse: {0}.
        /// </summary>
        public static string SnapshotModeControl_GlimpseFormat {
            get {
                return ResourceManager.GetString("SnapshotModeControl_GlimpseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Inspect page.
        /// </summary>
        public static string SnapshotModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("SnapshotModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No element is selected. please select an element first..
        /// </summary>
        public static string StartElementDetailViewNoElementIsSelectedMessage {
            get {
                return ResourceManager.GetString("StartElementDetailViewNoElementIsSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The select element is not available any more, please select a new one..
        /// </summary>
        public static string StartEventsModeElementNotAvailableMessage {
            get {
                return ResourceManager.GetString("StartEventsModeElementNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the selected file.
        ///Please ensure that you are opening a valid test file using the most recent release of Accessibility Insights for Windows (https://aka.ms/AccessibilityInsights)..
        /// </summary>
        public static string StartLoadingSnapshotLoadFileException {
            get {
                return ResourceManager.GetString("StartLoadingSnapshotLoadFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach now.
        /// </summary>
        public static string SupportDebuggingDialogMessage {
            get {
                return ResourceManager.GetString("SupportDebuggingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastPass.
        /// </summary>
        public static string tabControlLabelContent {
            get {
                return ResourceManager.GetString("tabControlLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to select:.
        /// </summary>
        public static string tbComboboxLabelText {
            get {
                return ResourceManager.GetString("tbComboboxLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated checks in FastPass.
        /// </summary>
        public static string tbiAutomatedChecksAutomationPropertiesName {
            get {
                return ResourceManager.GetString("tbiAutomatedChecksAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Checks.
        /// </summary>
        public static string tbiAutomatedChecksHeader {
            get {
                return ResourceManager.GetString("tbiAutomatedChecksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab stops in FastPass.
        /// </summary>
        public static string tbiTabStopAutomationPropertiesName {
            get {
                return ResourceManager.GetString("tbiTabStopAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Stops.
        /// </summary>
        public static string tbiTabStopHeader {
            get {
                return ResourceManager.GetString("tbiTabStopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Test in.
        /// </summary>
        public static string tbTimerText1 {
            get {
                return ResourceManager.GetString("tbTimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second(s).
        /// </summary>
        public static string tbTimerText2 {
            get {
                return ResourceManager.GetString("tbTimerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timer in.
        /// </summary>
        public static string tbxTimer_TextChangedText1 {
            get {
                return ResourceManager.GetString("tbxTimer_TextChangedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string tbxTimer_TextChangedText2 {
            get {
                return ResourceManager.GetString("tbxTimer_TextChangedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string tcTabsAboutHeader {
            get {
                return ResourceManager.GetString("tcTabsAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string tcTabsApplicationHeader {
            get {
                return ResourceManager.GetString("tcTabsApplicationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string tcTabsConnectionHeader {
            get {
                return ResourceManager.GetString("tcTabsConnectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or press Ctrl + I to go to Inspect mode, hover over the element within the target application, and select the Test icon.
        /// </summary>
        public static string TestModeControl_HoverAndTest {
            get {
                return ResourceManager.GetString("TestModeControl_HoverAndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run automated checks, select the Inspect tab.
        /// </summary>
        public static string TestModeControl_RunAutomatedChecks {
            get {
                return ResourceManager.GetString("TestModeControl_RunAutomatedChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test page.
        /// </summary>
        public static string TestModeControlAutomationPropertiesName {
            get {
                return ResourceManager.GetString("TestModeControlAutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string tests {
            get {
                return ResourceManager.GetString("tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color contrast.
        /// </summary>
        public static string TitleTextMapCCA {
            get {
                return ResourceManager.GetString("TitleTextMapCCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string TitleTextMapEvents {
            get {
                return ResourceManager.GetString("TitleTextMapEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events (Loaded data).
        /// </summary>
        public static string TitleTextMapEventsLoad {
            get {
                return ResourceManager.GetString("TitleTextMapEventsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events (Recording).
        /// </summary>
        public static string TitleTextMapEventsRecord {
            get {
                return ResourceManager.GetString("TitleTextMapEventsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string TitleTextMapEventsStopped {
            get {
                return ResourceManager.GetString("TitleTextMapEventsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting....
        /// </summary>
        public static string TitleTextMapExit {
            get {
                return ResourceManager.GetString("TitleTextMapExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect - Live.
        /// </summary>
        public static string TitleTextMapInspectLive {
            get {
                return ResourceManager.GetString("TitleTextMapInspectLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect (Scanning).
        /// </summary>
        public static string TitleTextMapInspectScan {
            get {
                return ResourceManager.GetString("TitleTextMapInspectScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TitleTextMapStart {
            get {
                return ResourceManager.GetString("TitleTextMapStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - Element details.
        /// </summary>
        public static string TitleTextMapTestElementDetails {
            get {
                return ResourceManager.GetString("TitleTextMapTestElementDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - How to Fix.
        /// </summary>
        public static string TitleTextMapTestHowToFix {
            get {
                return ResourceManager.GetString("TitleTextMapTestHowToFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - No selection.
        /// </summary>
        public static string TitleTextMapTestNoSelection {
            get {
                return ResourceManager.GetString("TitleTextMapTestNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - Test results.
        /// </summary>
        public static string TitleTextMapTestResults {
            get {
                return ResourceManager.GetString("TitleTextMapTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test (Scanning).
        /// </summary>
        public static string TitleTextMapTestScan {
            get {
                return ResourceManager.GetString("TitleTextMapTestScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test - Tab Stops.
        /// </summary>
        public static string TitleTextMapTestTabStops {
            get {
                return ResourceManager.GetString("TitleTextMapTestTabStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed into {0}.
        /// </summary>
        public static string UpdateMainWindowLoginFieldsSignedInAs {
            get {
                return ResourceManager.GetString("UpdateMainWindowLoginFieldsSignedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerelease Build ({0}).
        /// </summary>
        public static string VersionBarPreReleaseVersion {
            get {
                return ResourceManager.GetString("VersionBarPreReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter: Closing MainWindow.
        /// </summary>
        public static string Window_ClosingDebugMessage {
            get {
                return ResourceManager.GetString("Window_ClosingDebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while closing MainWindow.
        /// </summary>
        public static string Window_ClosingException {
            get {
                return ResourceManager.GetString("Window_ClosingException", resourceCulture);
            }
        }
    }
}
