//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axe.Windows.Rules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConditionDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConditionDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axe.Windows.Rules.Resources.ConditionDescriptions", typeof(ConditionDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllOf({0}).
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllChildren({0}).
        /// </summary>
        internal static string AllChildren {
            get {
                return ResourceManager.GetString("AllChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnyOf({0}).
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnyChild({0}).
        /// </summary>
        internal static string AnyChild {
            get {
                return ResourceManager.GetString("AnyChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoundingRectangle completely obscures container.
        /// </summary>
        internal static string BoundingRectangleCompletelyObscuresContainer {
            get {
                return ResourceManager.GetString("BoundingRectangleCompletelyObscuresContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountChildren({0}).
        /// </summary>
        internal static string ChildCount {
            get {
                return ResourceManager.GetString("ChildCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to children exist.
        /// </summary>
        internal static string ChildrenExist {
            get {
                return ResourceManager.GetString("ChildrenExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom landmark.
        /// </summary>
        internal static string CustomLandmark {
            get {
                return ResourceManager.GetString("CustomLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescendantCount({0}).
        /// </summary>
        internal static string DescendantCount {
            get {
                return ResourceManager.GetString("DescendantCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExactlyOne({0}).
        /// </summary>
        internal static string ExactlyOne {
            get {
                return ResourceManager.GetString("ExactlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form landmark.
        /// </summary>
        internal static string FormLandmark {
            get {
                return ResourceManager.GetString("FormLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heading level.
        /// </summary>
        internal static string HeadingLevel {
            get {
                return ResourceManager.GetString("HeadingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsContentElement.
        /// </summary>
        internal static string IsContentElement {
            get {
                return ResourceManager.GetString("IsContentElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsControlElement.
        /// </summary>
        internal static string IsControlElement {
            get {
                return ResourceManager.GetString("IsControlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main landmark.
        /// </summary>
        internal static string MainLandmark {
            get {
                return ResourceManager.GetString("MainLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navigation landmark.
        /// </summary>
        internal static string NavigationLandmark {
            get {
                return ResourceManager.GetString("NavigationLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoChild({0}).
        /// </summary>
        internal static string NoChild {
            get {
                return ResourceManager.GetString("NoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no children exist.
        /// </summary>
        internal static string NoChildrenExist {
            get {
                return ResourceManager.GetString("NoChildrenExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not({0}).
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1}.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string Parentheses {
            get {
                return ResourceManager.GetString("Parentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search landmark.
        /// </summary>
        internal static string SearchLandmark {
            get {
                return ResourceManager.GetString("SearchLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountSiblings({0}).
        /// </summary>
        internal static string SiblingCount {
            get {
                return ResourceManager.GetString("SiblingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to treeitem children exist .
        /// </summary>
        internal static string TreeItemChildrenExist {
            get {
                return ResourceManager.GetString("TreeItemChildrenExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
