//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessibilityInsights.VersionSwitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessibilityInsights.VersionSwitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line: {0}.
        /// </summary>
        public static string BadCommandLineMessageFormat {
            get {
                return ResourceManager.GetString("BadCommandLineMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installer file does not match the expected checksum and may have been corrupted. Please try again..
        /// </summary>
        public static string InstallerFileHasWrongHash {
            get {
                return ResourceManager.GetString("InstallerFileHasWrongHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installer file lacks a trusted signature and may have been corrupted. Please try again..
        /// </summary>
        public static string InstallerFileIsNotTrusted {
            get {
                return ResourceManager.GetString("InstallerFileIsNotTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installer file does not match the expected size and may have been corrupted. Please try again..
        /// </summary>
        public static string InstallerFileIsWrongSize {
            get {
                return ResourceManager.GetString("InstallerFileIsWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during install.
        /// </summary>
        public static string InstallError {
            get {
                return ResourceManager.GetString("InstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}% complete.
        /// </summary>
        public static string ProgressIndicatorFormat {
            get {
                return ResourceManager.GetString("ProgressIndicatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the installation. Please restart your computer and try again. If that does not resolve the issue, try removing Accessibility Insights for Windows via the control panel and install it from www.accessibilityinsights.io..
        /// </summary>
        public static string UnableToCompleteInstallation {
            get {
                return ResourceManager.GetString("UnableToCompleteInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download the installer file. Please check your internet connection and try again..
        /// </summary>
        public static string UnableToDownloadInstallerFile {
            get {
                return ResourceManager.GetString("UnableToDownloadInstallerFile", resourceCulture);
            }
        }
    }
}
