//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axe.Windows.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axe.Windows.Automation.DisplayStrings", typeof(DisplayStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation009: AxeWindows has already been started.
        /// </summary>
        internal static string ErrorAlreadyStarted {
            get {
                return ResourceManager.GetString("ErrorAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation001: Can&apos;t find secondary config file: {0}.
        /// </summary>
        internal static string ErrorCantFindSecondaryConfigFileFormat {
            get {
                return ResourceManager.GetString("ErrorCantFindSecondaryConfigFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation013: No data found in secondary config file: {0}.
        /// </summary>
        internal static string ErrorEmptySecondaryConfigFile {
            get {
                return ResourceManager.GetString("ErrorEmptySecondaryConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation017: Fail to get the root element of a process({0}) : {1}.
        /// </summary>
        internal static string ErrorFailToGetRootElementOfProcess {
            get {
                return ResourceManager.GetString("ErrorFailToGetRootElementOfProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation016: The file format is invalid.
        /// </summary>
        internal static string ErrorInvalidOutputFileFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidOutputFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation014: Can&apos;t load data from secondary config file: {0}.
        /// </summary>
        internal static string ErrorInvalidSecondaryConfigFile {
            get {
                return ResourceManager.GetString("ErrorInvalidSecondaryConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation012: ScanResults are missing. Please check configuration..
        /// </summary>
        internal static string ErrorMissingScanResults {
            get {
                return ResourceManager.GetString("ErrorMissingScanResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation007: No process Id is set.
        /// </summary>
        internal static string ErrorNoProcessIdSet {
            get {
                return ResourceManager.GetString("ErrorNoProcessIdSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation011: AxeWindows has not yet been started, or has already been stopped.
        /// </summary>
        internal static string ErrorNotStarted_Clear {
            get {
                return ResourceManager.GetString("ErrorNotStarted_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation010: AxeWindows has not yet been started, or has already been stopped.
        /// </summary>
        internal static string ErrorNotStarted_Instance {
            get {
                return ResourceManager.GetString("ErrorNotStarted_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation015: OutputFileFormat is missing and OutputFileName does not have an extension.
        /// </summary>
        internal static string ErrorOutputFileFormatIsTrivial {
            get {
                return ResourceManager.GetString("ErrorOutputFileFormatIsTrivial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation005: OutputFile is not specified.
        /// </summary>
        internal static string ErrorOutputFileIsNotSpecified {
            get {
                return ResourceManager.GetString("ErrorOutputFileIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation006: OutputFile is trivial.
        /// </summary>
        internal static string ErrorOutputFileIsTrivial {
            get {
                return ResourceManager.GetString("ErrorOutputFileIsTrivial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation004: OutputPath is trivial.
        /// </summary>
        internal static string ErrorOutputPathIsTrivial {
            get {
                return ResourceManager.GetString("ErrorOutputPathIsTrivial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation009: AxeWindows has already been started.
        /// </summary>
        internal static string ErrorStartAlreadyStarted {
            get {
                return ResourceManager.GetString("ErrorStartAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation017: Unable to set Data context (more than {0:N0} elements were found).
        /// </summary>
        internal static string ErrorTooManyElementsToSetDataContext {
            get {
                return ResourceManager.GetString("ErrorTooManyElementsToSetDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation008: Unable to set Data context.
        /// </summary>
        internal static string ErrorUnableToSetDataContext {
            get {
                return ResourceManager.GetString("ErrorUnableToSetDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Automation003: Unhandled Exception {0}.
        /// </summary>
        internal static string ErrorUnhandledExceptionFormat {
            get {
                return ResourceManager.GetString("ErrorUnhandledExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Results discarded, per command parameters).
        /// </summary>
        internal static string SnapshotDetailNoViolationsDataDiscarded {
            get {
                return ResourceManager.GetString("SnapshotDetailNoViolationsDataDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Results retained in {0}).
        /// </summary>
        internal static string SnapshotDetailNoViolationsDataRetainedFormat {
            get {
                return ResourceManager.GetString("SnapshotDetailNoViolationsDataRetainedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} violations(s) were found, as well as {1} inconclusive results. Results are retained in {2}.
        /// </summary>
        internal static string SnapshotDetailViolationsFormat {
            get {
                return ResourceManager.GetString("SnapshotDetailViolationsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxeWindows successfully started.
        /// </summary>
        internal static string SuccessStart {
            get {
                return ResourceManager.GetString("SuccessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxeWindows successfully stopped.
        /// </summary>
        internal static string SuccessStop {
            get {
                return ResourceManager.GetString("SuccessStop", resourceCulture);
            }
        }
    }
}
